car_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from car_project import settings
from django.conf.urls.i18n import i18n_patterns
from pages.views import SendFormEmail, HomeSendFormEmail

handler404 = 'pages.views.my_404'

urlpatterns = [
    path('admin/abai', admin.site.urls),

]
urlpatterns += i18n_patterns(
    path('cars/', include('cars.urls')),
    path('users/', include('users.urls')),
    path('charges/', include('charges.urls')),
    path('agreement/', include('agreement.urls')),
    path('', include('pages.urls')),
    path('reservations/', include('reservations.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home-send-form-email/', HomeSendFormEmail.as_view(), name='home_send_email'),
    path('send-form-email/', SendFormEmail.as_view(), name='send_email'),
    path('i18n/', include('django.conf.urls.i18n')),

    #API

    path("api-v1/", include("api_v1.urls")),
    prefix_default_language=False,
)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from .views import CarsListView, CategoryBListView, CategoryCListView, CategoryEListView, CategoryJListView, \
    CarDetailView, CarCreateView, CarUpdateView, CarDeleteView, FunctionListView, FunctionDeleteView, FunctionCreateView

urlpatterns = [
    path('', CarsListView.as_view(), name='cars_list'),
    path('<int:pk>/', CarDetailView.as_view(), name='car_detail'),
    path('create/', CarCreateView.as_view(), name='car_create'),
    path('<int:pk>/edit/', CarUpdateView.as_view(), name='car_update'),
    path('<int:pk>/delete', CarDeleteView.as_view(), name='car_delete'),
    path('class_b/', CategoryBListView.as_view(), name='class_b'),
    path('class_c/', CategoryCListView.as_view(), name='class_c'),
    path('class_e/', CategoryEListView.as_view(), name='class_e'),
    path('class_j/', CategoryJListView.as_view(), name='class_j'),
    path('func_list/', FunctionListView.as_view(), name='func_list'),
    path('func_delete/<int:pk>/', FunctionDeleteView.as_view(), name='func_delete'),
    path('func_create/', FunctionCreateView.as_view(), name='func_create'),
]

users/models.py
from django.db import models


class Users(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя')
    second_name = models.CharField(max_length=255, verbose_name='Фамилия', null=True, blank=True)
    last_name = models.CharField(max_length=255, verbose_name='Отчество', null=True, blank=True)
    birthday = models.DateField(verbose_name='День рождение', null=True, blank=True)
    phone = models.CharField(max_length=255, verbose_name='Телефон')
    email = models.CharField(max_length=255, verbose_name='Почта', null=True, blank=True)
    drivers_licence = models.CharField(max_length=255, verbose_name='Права')
    drivers_licence_img = models.ImageField(upload_to='users/', default='default.png')
    drivers_series = models.CharField(max_length=255, verbose_name='Серия прав', null=True, blank=True)
    drivers_number = models.CharField(max_length=255, verbose_name='Номер прав', null=True, blank=True)
    experience = models.CharField(max_length=255, verbose_name='Стаж')
    passport_doled_out = models.DateField(verbose_name='Паспорт выдан', null=True, blank=True)
    passport_series = models.CharField(max_length=255, verbose_name='Серия паспорта', null=True, blank=True)
    passport_number = models.CharField(max_length=255, verbose_name='Номер паспорт', null=True, blank=True)
    passport_issued = models.CharField(max_length=255, verbose_name="Кем выдан", null=True, blank=True)
    passport_img = models.ImageField(upload_to='users/', default='default.png')
    address = models.CharField(max_length=255, verbose_name='Адрес')

    def __str__(self):
        return f'{self.name} {self.phone}'

templates/manager/car_manager.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">БД Машин </h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>БД Машин</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>


    <!--=================================
     inner-intro -->
    <section class="welcome-block objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <a href="{% url 'car_create' %}" class="btn btn-danger mb-3">Добавить машину</a>
                |
                <a href="{% url 'func_list' %}" class="btn btn-danger mb-3">Список функций</a>

            </div>
            <div class="row">
                <table class="table table-hover">
                    <tr>
                        <th>Собственник</th>
                        <th>Марка авто</th>
                        <th>Номер машины</th>
                        <th>Год</th>
                        <th>Цвет</th>
                        <th>Управление</th>
                    </tr>
                    {% for x in cars %}
                        <tr>
                            <td>{{ x.car_owner }}</td>
                            <td>{{ x.title }}</td>
                            <td>{{ x.car_number }}</td>
                            <td>{{ x.year }}</td>
                            <td>{{ x.car_color }}</td>
                            <td>
                                <a href="{% url 'car_update' x.pk %}" class="btn">Изменить</a>
                                <a href="{% url 'car_delete' x.pk %}" class="btn">Удалить</a>
                                <a href="{% url 'car_detail' x.pk %}" class="btn">Подробнее</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </section>


{% endblock %}

templates/manager/function_manager.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">БД Функций </h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>БД Функций</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>


    <!--=================================
     inner-intro -->
    <section class="welcome-block objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <a href="{% url 'func_create' %}" class="btn btn-danger mb-3">Добавить функцию</a>
            </div>
            <div class="row">
                <table class="table table-hover">
                    <tr>
                        <th>Function</th>
                        <th>Функция</th>
                        <th>Управление</th>
                    </tr>
                    {% for x in object_list %}
                        <tr>
                            <td>{{ x.title }}</td>
                            <td>{{ x.title_rus }}</td>
                            <td>
                                <a href="{% url 'func_delete' x.pk %}" class="btn">Удалить</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </section>


{% endblock %}

templates/manager/manager_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Админ панель </h1>
                    <a href="{% url 'logout' %}" class="btn btn-danger">Выход</a>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><span>Админ панель</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!--=================================
     inner-intro -->
    <section class="welcome-block objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 manager_list">
                    <a href="{% url 'car_manager' %}">
                        <div class="feature-box text-center">
                            <div class="icon mb-3">
                                <img src="{% static 'images/service/traffic.png' %}" alt="">
                            </div>
                            <div class="content">
                                <h6>БД Машин</h6>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 manager_list">
                    <a href="{% url 'users_list' %}">
                        <div class="feature-box text-center">
                            <div class="icon mb-3">
                                <img src="{% static 'images/service/group.png' %}" alt="">
                            </div>
                            <div class="content">
                                <h6>БД Клиентов</h6>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 manager_list">
                    <a href="{% url 'income' %}">
                        <div class="feature-box text-center">
                            <div class="icon mb-3">
                                <img src="{% static 'images/service/pay.png' %}" alt="">
                            </div>
                            <div class="content">
                                <h6>Доход</h6>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 manager_list">
                    <a href="{% url 'outcome' %}">
                        <div class="feature-box text-center">
                            <div class="icon mb-3">
                                <img src="{% static 'images/service/bill.png' %}" alt="">
                            </div>
                            <div class="content">
                                <h6>Расход</h6>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 manager_list">
                    <a href="{% url 'profit' %}">
                        <div class="feature-box text-center">
                            <div class="icon mb-3">
                                <img src="{% static 'images/service/money.png' %}" alt="">
                            </div>
                            <div class="content">
                                <h6>Прибыль</h6>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 manager_list">
                    <a href="{% url 'reserve_list' %}">
                        <div class="feature-box text-center">
                            <div class="icon mb-3">
                                <img src="{% static 'images/service/calendar.png' %}" alt="">
                            </div>
                            <div class="content">
                                <h6>Календарь</h6>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 manager_list">
                    <a href="{% url 'agrement_list' %}">
                        <div class="feature-box text-center">
                            <div class="icon mb-3">
                                <img src="{% static 'images/service/deal.png' %}" alt="">
                            </div>
                            <div class="content">
                                <h6>Список договоров</h6>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 manager_list">
                    <a href="{% url 'service_manager' %}">
                        <div class="feature-box text-center">
                            <div class="icon mb-3">
                                <img src="{% static 'images/service/hr.png' %}" alt="">
                            </div>
                            <div class="content">
                                <h6>Услуги</h6>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

templates/manager/service_create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_field %}
{% load crispy_forms_utils %}
{% load crispy_forms_tags %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Добавить услугу </h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>Добавить услугу</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!--=================================
    inner-intro -->
    <section class="objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="col-md-6">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.name|as_crispy_field }}
                    {{ form.name_rus|as_crispy_field }}
                    {{ form.description|as_crispy_field }}
                    {{ form.description_rus|as_crispy_field }}
                    {{ form.price|as_crispy_field }}
                    {{ form.image|as_crispy_field }}

                    <button type="submit" class="btn btn-success">Создать</button>
                </form>
            </div>
            <div class="h30">&nbsp;</div>

        </div>
    </section>

{% endblock %}

templates/manager/service_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Удалить услугу <b>{{ object.name }}</b></h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i></li>
                        <li><span>Удалить услугу</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

     <!--=================================
     inner-intro -->
    <section class="objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="col-md-12">
                <form action="" method="post">
                    {% csrf_token %}
                    <p>Вы желаете удалить <b>{{ object.name }}</b></p>
                    <button type="submit" class="btn btn-success">Да</button>
                    <a href="{% url 'service_manager' %}" class="btn btn-danger">Нет</a>
                </form>
            </div>


        </div>
    </section>

{% endblock %}

templates/manager/service_manager.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Список услуг </h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>Список услуг</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>


    <!--=================================
     inner-intro -->
    <section class="welcome-block objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <a href="{% url 'service_create' %}" class="btn btn-danger mb-3">Добавить Услугу</a>
            </div>
            <div class="row">
                <table class="table table-hover">
                    <tr>
                        <th>#</th>
                        <th>Название услуги</th>
                        <th>Цена</th>
                    </tr>
                    {% for x in service %}
                        <tr>
                            <td></td>
                            <td>{{ x.name }}</td>
                            <td>{{ x.description }}</td>
                            <td>
                                <a href="{% url 'service_delete' x.pk %}" class="btn">Удалить</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </section>


{% endblock %}