car_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from car_project import settings
from django.conf.urls.i18n import i18n_patterns
from pages.views import SendFormEmail, HomeSendFormEmail

handler404 = 'pages.views.my_404'

urlpatterns = [
    path('admin/abai', admin.site.urls),

]
urlpatterns += i18n_patterns(
    path('cars/', include('cars.urls')),
    path('users/', include('users.urls')),
    path('charges/', include('charges.urls')),
    path('agreement/', include('agreement.urls')),
    path('', include('pages.urls')),
    path('reservations/', include('reservations.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home-send-form-email/', HomeSendFormEmail.as_view(), name='home_send_email'),
    path('send-form-email/', SendFormEmail.as_view(), name='send_email'),
    path('i18n/', include('django.conf.urls.i18n')),

    #API

    path("api-v1/", include("api_v1.urls")),
    prefix_default_language=False,
)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from .views import CarsListView, CategoryBListView, CategoryCListView, CategoryEListView, CategoryJListView, \
    CarDetailView, CarCreateView, CarUpdateView, CarDeleteView, FunctionListView, FunctionDeleteView, FunctionCreateView

urlpatterns = [
    path('', CarsListView.as_view(), name='cars_list'),
    path('<int:pk>/', CarDetailView.as_view(), name='car_detail'),
    path('create/', CarCreateView.as_view(), name='car_create'),
    path('<int:pk>/edit/', CarUpdateView.as_view(), name='car_update'),
    path('<int:pk>/delete', CarDeleteView.as_view(), name='car_delete'),
    path('class_b/', CategoryBListView.as_view(), name='class_b'),
    path('class_c/', CategoryCListView.as_view(), name='class_c'),
    path('class_e/', CategoryEListView.as_view(), name='class_e'),
    path('class_j/', CategoryJListView.as_view(), name='class_j'),
    path('func_list/', FunctionListView.as_view(), name='func_list'),
    path('func_delete/<int:pk>/', FunctionDeleteView.as_view(), name='func_delete'),
    path('func_create/', FunctionCreateView.as_view(), name='func_create'),
]

charges/urls.py
from django.urls import path
from charges.views import ProfitListView, IncomeListView, IncomeCreateView, IncomeUpdateView, IncomeDeleteView,\
    OutcomeListView, OutcomeCreateView, charges_default, export_users_xls

urlpatterns = [
    path('income/', IncomeListView.as_view(), name='income'),
    path('income/create/', IncomeCreateView.as_view(), name='income_create'),
    path('income/<int:pk>/update/', IncomeUpdateView.as_view(), name='income_update'),
    path('income/<int:pk>/delete/', IncomeDeleteView.as_view(), name='income_delete'),
    path('outcome/', OutcomeListView.as_view(), name='outcome'),
    path('profit/', ProfitListView.as_view(), name='profit'),
    path('outcome/create/', OutcomeCreateView.as_view(), name='outcome_create'),
    path('charges_dflt', charges_default, name='default'),
    path('xls/', export_users_xls, name='export_xls'),
]

charges/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from _datetime import datetime

from django.db.models.signals import post_save, pre_save, pre_delete
from django.dispatch import receiver

import cars


class Income(models.Model):
    income_reserve_id = models.IntegerField()
    car_income_id = models.ForeignKey('cars.Car', on_delete=models.CASCADE, verbose_name='ID Машины')
    income_amount = models.IntegerField(verbose_name='Сумма')
    order_date = models.DateTimeField(default=datetime.now, verbose_name="Дата")

    def __str__(self):
        return f'{self.car_income_id} | Cумма: {self.income_amount}'


class Outcome(models.Model):
    outcome_reserve_id = models.IntegerField(blank=True, null=True)
    outcome_remark = models.CharField(max_length=255, blank=True, null=True, verbose_name='Комментарии')
    car_outcome_id = models.ForeignKey('cars.Car', on_delete=models.CASCADE, verbose_name='ID Машины')
    outcome_amount = models.IntegerField(verbose_name='Сумма')
    order_date = models.DateTimeField(default=datetime.now, verbose_name="Дата")

    def __str__(self):
        return f'{self.car_outcome_id} | Cумма: {self.outcome_amount}'


class Profit(models.Model):
    car_profit_id = models.ForeignKey('cars.Car', on_delete=models.CASCADE, verbose_name='ID Машины')
    amount = models.IntegerField(verbose_name='Сумма', default=0)

    def __str__(self):
        return f'{self.car_profit_id} | Cумма: {self.amount}'


@receiver(post_save, sender=Income)
def car_income(sender, instance, created, **kwargs):
    if created:
        car = Profit.objects.get(car_profit_id=instance.car_income_id)
        car.amount = car.amount + instance.income_amount
        car.save()


@receiver(pre_save, sender=Income)
def car_income_change(sender, instance, **kwargs):
    try:
        income = Income.objects.get(id=instance.id)
        car = Profit.objects.get(car_profit_id=instance.car_income_id)
        car.amount = car.amount + instance.income_amount - income.income_amount
        car.save()
    except ObjectDoesNotExist:
        pass


@receiver(pre_delete, sender=Income)
def car_income_delete(sender, instance, **kwargs):
    income = Income.objects.get(id=instance.id)
    car = Profit.objects.get(car_profit_id=instance.car_income_id)
    car.amount = car.amount - income.income_amount
    car.save()


@receiver(post_save, sender=Outcome)
def car_outcome(sender, created, instance, **kwargs):
    if created:
        car = Profit.objects.get(car_profit_id=instance.car_outcome_id)
        car.amount = car.amount - instance.outcome_amount
        car.save()


@receiver(pre_save, sender=Outcome)
def car_outcome_change(sender, instance, **kwargs):
    try:
        outcome = Outcome.objects.get(id=instance.id)
        car = Profit.objects.get(car_profit_id=instance.car_outcome_id)
        car.amount = car.amount - instance.outcome_amount + outcome.outcome_amount
        car.save()
    except ObjectDoesNotExist:
        pass


@receiver(pre_delete, sender=Outcome)
def car_outcome_delete(sender, instance, **kwargs):
    outcome = Outcome.objects.get(id=instance.id)
    car = Profit.objects.get(car_profit_id=instance.car_outcome_id)
    car.amount = car.amount + outcome.outcome_amount
    car.save()

charges/forms.py
from django import forms
from charges.models import Income, Outcome


class IncomeForm(forms.ModelForm):
    model = Income
    fields = "__all__"

charges/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views import View

from .models import Income, Outcome, Profit
from django.views.generic import ListView, UpdateView, DetailView, DeleteView, CreateView

import xlwt
from _datetime import datetime


class IncomeListView(ListView):
    model = Income
    template_name = 'charges/income.html'


class IncomeCreateView(CreateView):
    model = Income
    template_name = 'charges/income_create.html'
    fields = '__all__'
    success_url = reverse_lazy('income')


class IncomeUpdateView(UpdateView):
    model = Income
    template_name = 'charges/income_update.html'
    fields = '__all__'
    success_url = reverse_lazy('income')


class IncomeDeleteView(DeleteView):
    model = Income
    template_name = 'charges/income_delete.html'
    success_url = reverse_lazy('income')


class OutcomeListView(ListView):
    model = Outcome
    template_name = 'charges/outcome.html'


class ProfitListView(ListView):
    model = Profit
    template_name = 'charges/profit.html'


class OutcomeCreateView(CreateView):
    model = Outcome
    template_name = 'charges/outcome_create.html'
    fields = ('car_outcome_id', 'outcome_amount', 'outcome_remark')
    success_url = reverse_lazy('outcome')


def charges_default(request):
    income = Income.objects.all()
    outcome = Outcome.objects.all()
    income.delete()
    outcome.delete()
    return redirect('profit')


def export_users_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="City_Rent_{date}.xls"'.format(
        date=datetime.now().strftime(
            '%d-%m-%Y'))

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('{date}.xls'.format(
        date=datetime.now().strftime(
            '%d-%m-%Y')))
    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    font_style.font.colour_index = 4
    font_style.font.height = 280
    column = ['Отчет за {date}'.format(
        date=datetime.now().strftime(
            '%B %Y'))]
    ws.write(row_num, 3, column, font_style)
    row_num += 2

    font_style.font.height = 240
    column = ['Доходы']
    ws.write(row_num, 3, column, font_style)
    row_num += 1

    font_style.font.height = 220
    columns = ['Машина', 'Номер машины', 'Сумма', 'Дата', ]
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()
    rows = Income.objects.order_by('id') \
        .values_list('car_income_id__title', 'car_income_id__car_number',
                     'income_amount', 'order_date')

    rows = [[x.strftime("%d-%m-%Y") if isinstance(x, datetime) else x for x in row] for row in rows]
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)
    row_num += 2

    # Расходы
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    font_style.font.colour_index = 4
    font_style.font.height = 240
    column = ['Расходы']
    ws.write(row_num, 3, column, font_style)
    row_num += 1

    font_style.font.height = 220
    columns = ['Машина', 'Номер машины', 'Сумма', 'Дата', 'Ремарка', ]
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()
    outcome_rows = Outcome.objects.order_by('id') \
        .values_list('car_outcome_id__title', 'car_outcome_id__car_number',
                     'outcome_amount', 'order_date', 'outcome_remark')

    outcome_rows = [[x.strftime("%d-%m-%Y") if isinstance(x, datetime) else x for x in row] for row in outcome_rows]
    for row in outcome_rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)
    row_num += 2

    # Прибыль
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    font_style.font.colour_index = 4
    font_style.font.height = 240
    column = ['Прибыль']
    ws.write(row_num, 3, column, font_style)
    row_num += 1

    font_style.font.height = 220
    columns = ['Машина', 'Номер машины', 'Сумма', ]
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()
    rows = Profit.objects.order_by('id') \
        .values_list('car_profit_id__title', 'car_profit_id__car_number',
                     'amount')

    rows = [[x.strftime("%d-%m-%Y") if isinstance(x, datetime) else x for x in row] for row in rows]
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)
    row_num += 2

    wb.save(response)
    return response

templates/charges/income.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Доход </h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>Доход</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!--=================================
      inner-intro -->
    <section class="welcome-block objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <a href="{% url 'income_create' %}" class="btn btn-success mb-3">Добавить запись</a>

            </div>
            <div class="row">
                <table class="table table-bordered table-hover toggle-circle" id="exampleFootableFiltering"
                       data-paging="true" data-filtering="true" data-sorting="true">
                    <tr>
                        <th data-name="carName">Название машины</th>
                        <th data-name="balance">Сумма</th>
                        <th data-name="date">Дата</th>
                        <th data-name="management">Управление</th>
                    </tr>
                    {% for x in object_list %}
                        <tr class="show-hide-block">
                            <td class="income-car-title">{{ x.car_income_id }}</td>
                            <td>{{ x.income_amount }}</td>
                            <td>{{ x.order_date }}</td>
                            <td>
                                <a href="{% url 'income_update' x.pk %}" class="btn">Изменить</a>
                                <a href="{% url 'income_delete' x.pk %}" class="btn">Удалить</a>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <th class="profit-title">Общая прибыль</th>
                        <th class="profit"></th>
                    </tr>
                </table>
            </div>
        </div>


    </section>
    <script>
        let count = 0;
        {% for x in object_list %}
            count = count + +{{ x.income_amount }};
        {% endfor %}

        console.log(count);

        let profit = document.querySelector(".profit");

        profit.innerHTML = count;
    </script>
{% endblock %}

templates/charges/income_create.html
{% extends 'base.html' %}

{% block content %}
    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Создать расход </h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>Создать расход</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section class="welcome-block objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p><label for="id_car_id">ID автомобиля:</label>
{#                        <select name="car_outcome_id" class="form-control" required="" id="id_car_outcome_id">#}
{#                            <option value="" selected=""></option>#}
{#                            {% for car in cars %}#}
{#                                <option value="{{ car.id }}">{{ car.title }} ({{ car.car_color }})</option>#}
{#                            {% endfor %}#}
{#                            #}
{#                        </select>#}
                    <input type="number" class="form-control" name="car_id" required=""
                               id="id_car_id">
                    </p>
                    <p><label for="id_income_amount">Сумма:</label>
                        <input type="number" class="form-control" name="income_amount" required=""
                               id="id_income_amount">
                    </p>
                    <p><label for="id_outcome_remark">Заметки:</label>
                        <input type="text" class="form-control" name="outcome_remark" maxlength="255"
                               id="id_outcome_remark"></p>
                    <p>
                        <button type="submit" class="btn btn-success">Создать</button>
                    </p>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/charges/income_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Удалить запись <b>№{{ object.pk }}</b></h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i></li>
                        <li><span>Удалить запись</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

     <!--=================================
     inner-intro -->
    <section class="objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="col-md-12">
                <form action="" method="post">
                    {% csrf_token %}
                    <p>Вы желаете удалить запись <b>№{{ object.pk }}?</b></p>
                    <button type="submit" class="btn btn-success">Да</button>
                    <a href="javascript:history.back()" class="btn btn-danger">Нет</a>
                </form>
            </div>


        </div>
    </section>

{% endblock %}

templates/charges/outcome.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Расход </h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>Расход</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!--=================================
      inner-intro -->
    <section class="welcome-block objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <a href="{% url 'outcome_create' %}" class="btn btn-danger mb-3">Создать рассход</a>

            </div>
            <div class="row">
                <table class="table table-bordered table-hover toggle-circle" id="exampleFootableFiltering"
                       data-paging="true" data-filtering="true" data-sorting="true">
                    <tr>
                        <th data-name="carName">Название машины</th>
                        <th data-name="balance">Сумма</th>
                        <th>Комментарии</th>
                        <th data-name="date">Дата</th>
                    </tr>
                    {% for x in object_list %}
                        <tr>
                            <td>{{ x.car_outcome_id }}</td>
                            <td>{{ x.outcome_amount }}</td>
                            <td>{% if x.outcome_remark %}{{ x.outcome_remark }}{% endif %}</td>
                            <td>{{ x.order_date }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <th class="outcome-title">Общие расходы</th>
                        <th class="outcome"></th>
                    </tr>
                </table>
            </div>
        </div>
        </div>
        </div>

        <div class="h30">&nbsp;</div>

        <div class="conditionTab">
        </div>

        </div>
        </div>
    </section>

        <script>
        let count = 0;
        {% for x in object_list %}
            count = count + +{{ x.outcome_amount }};
        {% endfor %}

        console.log(count);

        let outcome = document.querySelector(".outcome");

        outcome.innerHTML = count;
    </script>
{% endblock %}

templates/charges/outcome_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Создать расход </h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>Создать расход</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!--=================================
    inner-intro -->
    <section class="welcome-block objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p><label for="id_car_outcome_id">Машина:</label>
                        <select name="car_outcome_id" class="form-control" required="" id="id_car_outcome_id">
                            <option value="" selected=""></option>
                            {% for car in cars %}
                                <option value="{{ car.id }}">{{ car.title }} ({{ car.car_color }})</option>
                            {% endfor %}
                        </select></p>
                    <p><label for="id_outcome_amount">Сумма:</label>
                        <input type="number" class="form-control" name="outcome_amount" required=""
                               id="id_outcome_amount">
                    </p>
                    <p><label for="id_outcome_remark">Заметки:</label>
                        <input type="text" class="form-control" name="outcome_remark" maxlength="255"
                               id="id_outcome_remark"></p>
                    <p>
                        <button type="submit" class="btn btn-success">Создать</button>
                    </p>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/charges/profit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Прибыль</h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>Прибыль</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!--=================================
      inner-intro -->
    <section class="welcome-block objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <a href="{% url 'default' %}" class="btn-borders">Сбросить</a>
                <a href="{% url 'export_xls' %}" class="btn-borders">Скачать Отчет</a>
            </div>
            <div class="row">
                <table class="table table-bordered table-hover toggle-circle" id="exampleFootableFiltering"
                       data-paging="true" data-filtering="true" data-sorting="true">
                    <tr>
                        <th data-name="carName">Название машины</th>
                        <th data-name="balance">Сумма</th>
                    </tr>
                    {% for x in object_list %}
                        <tr>
                            <td>{{ x.car_profit_id }}</td>
                            <td>{{ x.amount }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <th class="profit-title">Общая прибыль</th>
                        <th class="profit"></th>
                    </tr>
                </table>
            </div>
        </div>
    </section>


    <script>
        let count = 0;
        {% for x in object_list %}
            count = count + +{{ x.amount }};
        {% endfor %}

        console.log(count);

        let profit = document.querySelector(".profit");

        profit.innerHTML = count;
    </script>
{% endblock %}