agreement/urls.py
from django.urls import path
from .views import AgreementListView, AgreementCreateView, AgreementDetailView

urlpatterns = [
    path('', AgreementListView.as_view(), name='agrement_list'),
    path('<int:pk>/', AgreementDetailView.as_view(), name='agreement_detail'),
    path('create/<int:reserve_id>/', AgreementCreateView.as_view(), name='agreement_create'),
]

car_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from car_project import settings
from django.conf.urls.i18n import i18n_patterns
from pages.views import SendFormEmail, HomeSendFormEmail

handler404 = 'pages.views.my_404'

urlpatterns = [
    path('admin/abai', admin.site.urls),

]
urlpatterns += i18n_patterns(
    path('cars/', include('cars.urls')),
    path('users/', include('users.urls')),
    path('charges/', include('charges.urls')),
    path('agreement/', include('agreement.urls')),
    path('', include('pages.urls')),
    path('reservations/', include('reservations.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home-send-form-email/', HomeSendFormEmail.as_view(), name='home_send_email'),
    path('send-form-email/', SendFormEmail.as_view(), name='send_email'),
    path('i18n/', include('django.conf.urls.i18n')),

    #API

    path("api-v1/", include("api_v1.urls")),
    prefix_default_language=False,
)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path
from .views import CarsListView, CategoryBListView, CategoryCListView, CategoryEListView, CategoryJListView, \
    CarDetailView, CarCreateView, CarUpdateView, CarDeleteView, FunctionListView, FunctionDeleteView, FunctionCreateView

urlpatterns = [
    path('', CarsListView.as_view(), name='cars_list'),
    path('<int:pk>/', CarDetailView.as_view(), name='car_detail'),
    path('create/', CarCreateView.as_view(), name='car_create'),
    path('<int:pk>/edit/', CarUpdateView.as_view(), name='car_update'),
    path('<int:pk>/delete', CarDeleteView.as_view(), name='car_delete'),
    path('class_b/', CategoryBListView.as_view(), name='class_b'),
    path('class_c/', CategoryCListView.as_view(), name='class_c'),
    path('class_e/', CategoryEListView.as_view(), name='class_e'),
    path('class_j/', CategoryJListView.as_view(), name='class_j'),
    path('func_list/', FunctionListView.as_view(), name='func_list'),
    path('func_delete/<int:pk>/', FunctionDeleteView.as_view(), name='func_delete'),
    path('func_create/', FunctionCreateView.as_view(), name='func_create'),
]

agreement/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils.datetime_safe import datetime
from users.models import Users
from reservations.models import Reserve
from charges.models import Income


class Agreement(models.Model):
    registration_date = models.DateField(auto_now=True)
    reserve_id = models.ForeignKey(Reserve, on_delete=models.DO_NOTHING)
    # service = models.ManyToManyField('Service', verbose_name='Услуги', null=True, blank=True,)
    total = models.IntegerField()
    total_summ = models.IntegerField()
    territory_of_use = models.CharField(max_length=255, verbose_name='Территория использования ТС', null=True, blank=True)

    def __str__(self):
        return f'{self.registration_date}'


class Service(models.Model):
    name = models.CharField(max_length=255, verbose_name="Service name")
    name_rus = models.CharField(max_length=255, verbose_name="Наименование услуги")
    description = models.CharField(max_length=255, verbose_name="Service description")
    description_rus = models.CharField(max_length=255, verbose_name="Описание услуги")
    price = models.IntegerField(verbose_name='Цена услуги')
    image = models.ImageField(verbose_name='Картинка услуги', upload_to='service/', default='default.png')

    def __str__(self):
        return f'{self.name}'


@receiver(pre_save, sender=Agreement)
def agreement_check(sender, instance, **kwargs):
    try:
        agreement_id = Agreement.objects.get(reserve_id=instance.reserve_id.id)
        income_id = Income.objects.get(income_reserve_id=agreement_id.reserve_id.id)
        agreement_id.delete()
        income_id.delete()
    except ObjectDoesNotExist:
        pass


@receiver(post_save, sender=Agreement)
def agreement_income_add(sender, created, instance, **kwargs):
    try:
        income_id = Income.objects.get(income_reserve_id=instance.reserve_id.id)
    except ObjectDoesNotExist:
        income = Income.objects.create(income_reserve_id=instance.reserve_id.id,
                                       car_income_id=instance.reserve_id.reserve_car, income_amount=instance.total_summ)
        income.save()

agreement/forms.py
from django import forms

from agreement.models import Agreement


class AgreementCreateForm(forms.ModelForm):
    territory_of_use = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'г. Бишкек'}))

    class Meta:
        model = Agreement
        fields = '__all__'

agreement/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, DeleteView
from reservations.models import Reserve
import mimetypes
import os
from django.http.response import HttpResponse
from .forms import AgreementCreateForm
from .models import Agreement, Service


class AgreementListView(ListView):
    model = Agreement
    template_name = 'agreements/agreement_list.html'
    queryset = Agreement.objects.all()


class AgreementDetailView(DetailView):
    model = Agreement
    template_name = 'agreements/agreement_detail.html'


class AgreementCreateView(CreateView):
    model = Agreement
    template_name = 'agreements/agreement_create.html'
    form_class = AgreementCreateForm

    def get_context_data(self, **kwargs):
        context = super(AgreementCreateView, self).get_context_data(**kwargs)
        context['reserve_info'] = Reserve.objects.get(pk=self.kwargs['reserve_id'])
        return context

    def get_success_url(self):
        return reverse('agreement_detail', kwargs={'pk': self.object.pk})


def download_file(request):
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    filename = 'agreement.txt'
    filepath = BASE_DIR + '/CityRent/Files/' + filename
    path = open(filepath, 'r')
    mime_type, _ = mimetypes.guess_type(filepath)
    response = HttpResponse(path, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

templates/agreements/agreement_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Создать договор</h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>Создать договор</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!--=================================
     inner-intro -->
    <section class="objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="agreement-main">
                        <style>
                            p.hidden {
                                display: none;
                            }
                        </style>

                        <h2 class="agreement-main-title">Договор аренды:</h2>
                        <p class="hidden"><label for="id_reserve_id">Заказ:</label> <select name="reserve_id"
                                                                                            required=""
                                                                                            id="id_reserve_id">
                            <option value="{{ reserve_info.id }}" selected="">{{ reserve_info.reserve_car }}</option>
                        </select></p>
                        <table class="create-agr-content-main">
                            <tr class="create-agr-main">
                                <td class="create-agr-title thead-dark">Машина</td>
                                <td class="create-agr-content">{{ reserve_info.reserve_car }}</td>
                            </tr>
                            <tr class="create-agr-main">
                                <td class="create-agr-title thead-dark">Клиент</td>
                                <td class="create-agr-content">{{ reserve_info.users.name }} {{ reserve_info.users.second_name }} {{ reserve_info.users.last_name }}</td>
                            </tr>
                            <tr class="create-agr-main">
                                <td class="create-agr-title thead-dark">Начало:</td>
                                <td class="create-agr-content">{{ reserve_info.departure_date }}</td>
                            </tr>
                            <tr class="create-agr-main">
                                <td class="create-agr-title thead-dark">Дата бронирования</td>
                                <td class="create-agr-content">{{ reserve_info.registration_date }}</td>
                            </tr>
                            <tr class="create-agr-main">
                                <td class="create-agr-title thead-dark">Количество дней</td>
                                <td class="create-agr-content">{{ reserve_info.total_days }}</td>
                            </tr>
                            <tr class="create-agr-main">
                                <td class="create-agr-title thead-dark">Сумма</td>
                                <td class="create-agr-content"><input type="number" name="total" required=""
                                                                      value="{{ reserve_info.total_summ }}"
                                                                      id="id_total" class="agreement-inputs"></td>
                            </tr>
                            <tr class="create-agr-main">
                                <td class="create-agr-title thead-dark">Услуги</td>
                                <td class="create-agr-content"></td>
                            </tr>
                            {% for x in service %}
                                <tr class="create-agr-main">
                                    <td class="create-agr-title thead-dark">{{ x.name }}</td>
                                    <td class="create-agr-content"><input type="checkbox" id="id_service" name="service"
                                                                          value="{{ x.pk }}" price="{{ x.price }}"
                                                                          class="select-items"></td>
                                </tr>
                            {% endfor %}
                            <tr class="create-agr-main">
                                <td class="create-agr-title thead-dark">Итоговая сумма</td>
                                <td class="create-agr-content"><input class="summ agreement-inputs" type="number" name="total_summ"
                                                                      required=""
                                                                      value="{{ reserve_info.total_summ }}"></td>
                            </tr>
                            <tr class="create-agr-main">
                                <td class="create-agr-title thead-dark">Территория использования ТС</td>
                                <td class="create-agr-content"><input type="text" name="territory_of_use" class="agreement-inputs" value="{{ reserve_info.territory_of_use }}" placeholder="г. Бишкек"></td>
                            </tr>
                        </table>
                        {#                        <p><b>Машина:</b> {{ reserve_info.reserve_car }}</p>#}
                        {#                        <p>#}
                        {#                            <b>Клиент</b>: {{ reserve_info.users.name }} {{ reserve_info.users.second_name }} {{ reserve_info.users.last_name }}#}
                        {#                        </p>#}
                        {#                        <p><b>Начало</b>: {{ reserve_info.departure_date }}</p>#}
                        {#                        <p><b>Конец</b>: {{ reserve_info.arrival_date }}</p>#}
                        {#                        <p><b>Дата бронирования</b>: {{ reserve_info.registration_date }}</p>#}
                        {#                        <p><b>Количество дней</b>: {{ reserve_info.total_days }}</p>#}
                        {#                        <div class="main-service-items">#}
                        {#                            {% for x in service %}#}
                        {#                                <div class="select-content">#}
                        {#                                    <input type="checkbox" id="id_service" name="service"#}
                        {#                                           value="{{ x.pk }}" price="{{ x.price }}" class="select-items">#}
                        {#                                    <label for="service">{{ x.name }}</label>#}
                        {#                                </div>#}
                        {#                            {% endfor %}#}
                        {#                        </div>#}

{#                        </p>#}
{#                        <p><label for="id_total_summ"><b>Итоговая сумма</b>:</label>#}
{#                            <input class="summ" type="number" name="total_summ" required=""#}
{#                                   value="{{ reserve_info.total_summ }}">#}
{#                        </p>#}
{#                        <p><label for="id_territory_of_use"><b>Территория использования ТС</b>:</label>#}
{#                            <input type="text" name="territory_of_use" required=""#}
{#                                   value="{{ reserve_info.territory_of_use }}">#}
{#                        </p>#}

                        <button type="submit" class="btn btn-success btn-car-agreement">Создать</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <style>
        p,
        label {
            font: 1rem 'Fira Sans', sans-serif;
        }

        input {
            margin: .4rem;
        }

    </style>
    <script>

        Array.prototype.remove = function () {
            let what, a = arguments, L = a.length, ax;
            while (L && this.length) {
                what = a[--L];
                while ((ax = this.indexOf(what)) !== -1) {
                    this.splice(ax, 1);
                }
            }
            return this;
        };

        let summ = document.querySelector(".summ");
        let select = document.querySelector("#id_service");
        let total = document.querySelector("#id_total");
        let arr = [];
        let selectItem = document.querySelectorAll(".select-items");

        console.log(summ);

        let sum = 0;
        total.addEventListener("input", function () {
            sum = +total.value;
            for (let i = 0; i < arr.length; i++) {
                sum = sum + +arr[i].getAttribute("price");
            }
            summ.value = sum;
            console.log(sum);
        });


        selectItem.forEach(item => item.addEventListener("click", function () {
                for (let b = 0; b < selectItem.length; b++) {
                    if (!arr.includes(selectItem[b]) && selectItem[b].checked == true) {
                        arr.push(selectItem[b]);
                    } else if (selectItem[b].checked == false) {
                        arr.remove(selectItem[b]);
                    }
                }
                sum = +total.value;
                for (let i = 0; i < arr.length; i++) {
                    sum = sum + +arr[i].getAttribute("price");
                }
                summ.value = sum;

            })
        );
    </script>
{% endblock %}

templates/agreements/agreement_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!--=================================
     inner-intro -->

    <section class="inner-intro bg-1 bg-overlay-black-70">
        <div class="container">
            <div class="row text-center intro-title">
                <div class="col-md-6 text-md-left d-inline-block">
                    <h1 class="text-white">Список договоров</h1>
                </div>
                <div class="col-md-6 text-md-right float-right">
                    <ul class="page-breadcrumb">
                        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Главная</a> <i
                                class="fa fa-angle-double-right"></i></li>
                        <li><a href="{% url 'manager_list' %}">Админ панель</a> <i class="fa fa-angle-double-right"></i>
                        </li>
                        <li><span>Список договоров</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!--=================================
      inner-intro -->
    <section class="welcome-block objects-car why-choose page-section-ptb white-bg">
        <div class="container">
            <div class="row">
                <table class="table table-bordered table-hover toggle-circle" id="exampleFootableFiltering"
                       data-paging="true" data-filtering="true" data-sorting="true">
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>ФИО клиента</th>
                        <th>Марка модель</th>
                        <th>Начало</th>
                        <th>Окончание</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for x in object_list %}

                        <tr>
                            <td><a href="{% url 'agreement_detail' x.pk %}">№ {{ x.registration_date|date:"y" }} -
                                00{{ x.id }}</a></td>
                            <td>{{ x.reserve_id.users.second_name }} {{ x.reserve_id.users.name }} {{ x.reserve_id.users.last_name }}</td>
                            <td>{{ x.reserve_id.reserve_car.title }} {{ x.reserve_id.reserve_car.car_color }}</td>
                            <td>{{ x.reserve_id.departure_date }}</td>
                            <td>{{ x.reserve_id.arrival_date }}</td>
                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
{% endblock %}